### PR TITLE
AVM-Review-PR

### PR DESCRIPTION
**Pull request by chianw**
## Description
AVM core team please review the first release of this module. 

avm pre-commit and avm pr-checks have passed

Deployment of the default example is successful

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `locals.version.tf.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `locals.version.tf.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `locals.version.tf.json`.
  - [ ] Update to documentation

# Checklist

- [x ] I'm sure there are no other open Pull Requests for the same update/change
- [x ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x ] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by chianw** [comment]
Current e2e test fail as there is not sufficient CPU quotas on the test subscription. Please raise the CPU quotas 

image

**Comment by chianw** [comment]
The list of available SKUs for General Purpose dedicated hosts - https://learn.microsoft.com/en-us/azure/virtual-machines/dedicated-host-general-purpose-skus . For the e2e test to pass the subscription's CPU quota needs to be increased, please let me know for which SKU the CPU quota has been increased so that the e2e test passes. 

Note the smallest SKU "DCSv2-Type1" does not support a host group with automatic placement enabled.

**Comment by mbilalamjad** [comment]
> The list of available SKUs for General Purpose dedicated hosts - https://learn.microsoft.com/en-us/azure/virtual-machines/dedicated-host-general-purpose-skus . For the e2e test to pass the subscription's CPU quota needs to be increased, please let me know for which SKU the CPU quota has been increased so that the e2e test passes.
> 
> Note the smallest SKU "DCSv2-Type1" does not support a host group with automatic placement enabled.

@matt-FFFFFF, @lonegunmanb guys any advice on this

**Comment by chianw** [comment]
@mbilalamjad has the CPU quota on the test subscription been increased for e2e test to succeed?

**Comment by chianw** [comment]
HI @lonegunmanb I've changed the location of the example to eastus2 but still having the resource quota issue on the subscription 

image

**Comment by chianw** [comment]
> Hi @chianw apology for this quota issue, we've talked with Azure support team, unfortunately we cannot get extra quota in `eastus` region, but we've managed to increase our resource quota in `eastus2` region. Could you please try to change the location used in your example to `eastus2` and try again? Thanks!


Hi @lonegunmanb I've changed the location of the example to eastus2 but still having the resource quota issue on the subscription

image

**Comment by chianw** [comment]
Hi @lonegunmanb any advice on https://github.com/Azure/terraform-azurerm-avm-res-compute-hostgroup/pull/26#issuecomment-2219598163 ?

**Comment by chianw** [comment]
Hi  @lonegunmanb  and @mbilalamjad , I tried to use a smaller host size DCSv2-Type1 in EastUS (this is not available in EastUS2)  after setting automatic_placement_enabled to false but still hitting into resource quota limits on the subscription. Please assist.


image

**Pull request merged**
